[package]
name = "SMReplace"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls"] }
